export const sampleEvents = [
  {
    id: "evt1",
    title: "Team Sync",
    startDate: "2025-07-15",
    endDate: "2025-07-15",
    startTime: "10:00",
    endTime: "11:00",
    location: "Conference Room A",
    description: "Weekly team synchronization meeting.",
    color: "#007bff",
    recurrence: { rule: "weekly", until: "2025-12-31" },
  },
  {
    id: "evt2",
    title: "Project Alpha Deadline",
    startDate: "2025-07-20",
    endDate: "2025-07-20",
    startTime: "",
    endTime: "",
    location: "",
    description: "Final submission for Project Alpha.",
    color: "#dc3545",
    recurrence: { rule: "none" },
  },
  {
    id: "evt3",
    title: "Design Review",
    startDate: "2025-07-01",
    endDate: "2025-07-01",
    startTime: "14:00",
    endTime: "15:30",
    location: "Online",
    description: "Review of the new UI mockups.",
    color: "#28a745",
    recurrence: { rule: "none" },
  },
  {
    id: "evt4",
    title: "Annual Company Retreat",
    startDate: "2025-08-08",
    endDate: "2025-08-10",
    startTime: "",
    endTime: "",
    location: "Mountain Resort",
    description: "Yearly company-wide retreat.",
    color: "#ffc107",
    recurrence: { rule: "none" },
  },
];
